import { Layout, Toaster } from "@/app/lib/@frontend/ui";
import type { Metadata } from "next";
import NextJsTopLoader from "nextjs-toploader";
import "./globals.css";

export const metadata: Metadata = {
  title: "BErp",
  description: "Generated by bsoft",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Layout>
      <NextJsTopLoader color="#a855f7" />
      {children}
      <Toaster />
    </Layout>
  );
}
