import type { Metadata } from "next";
import "./globals.css";
import { Layout } from "./ui";

export const metadata: Metadata = {
  title: "BStock",
  description: "Generated by bsoft",
};
import { Toaster } from "@/app/ui/toaster";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Layout>
      {children}
      <Toaster />
    </Layout>
  );
}
