import { Layout, Toaster } from "@/app/lib/@frontend/ui/component";
import type { Metadata } from "next";
import HolyLoader from "holy-loader";
import "./globals.css";

export const metadata: Metadata = {
  title: "BCube",
  description: "Generated by bsoft",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Layout>
      <HolyLoader
        color="linear-gradient(to right, #FFB80E, #FF1BD4, #0FAAEC)"
        speed={250}
        easing="linear"
        showSpinner
      />
      {children}
      <Toaster />
    </Layout>
  );
}
