import { z } from "zod";

export const SaleOrderOmieSchema = z.object({
  messageId: z.string(),
  topic: z.enum([
    "VendaProduto.Incluida",
    "VendaProduto.Alterada",
    "VendaProduto.Excluida",
    "VendaProduto.EtapaAlterada",
    "VendaProduto.Cancelada",
  ]),
  event: z.object({
    cancelada: z.enum(["S", "N"]).optional(),
    codIntPedido: z.string(),
    codigoCategoria: z.string(),
    dataInclusao: z.string().optional(),
    dataCancelado: z.string().optional(),
    dataPrevisao: z.string(),
    dataAlteracao: z.string().optional(),
    etapa: z.enum(["00", "20", "60", "70", "50", "80", "10"]),
    etapaDescr: z.enum([
      "Proposta",
      "Separar Estoque",
      "Faturado",
      "Entrega",
      "Faturar",
      "Pedido/ Aprovação Financeira",
      "Proposta/ Orçamento",
    ]),
    horaInclusao: z.string().optional(),
    horaAlteracao: z.string().optional(),
    horaCancelado: z.string().optional(),
    idCliente: z.number(),
    idContaCorrente: z.number(),
    idPedido: z.number(),
    numeroPedido: z.string(),
    usuarioInclusao: z.string().optional(),
    usuarioAlteracao: z.string().optional(),
    usuarioCancelado: z.string().optional(),
    valorPedido: z.number(),
  }),
  author: z.object({
    email: z.string().email(),
    name: z.string(),
    userId: z.number(),
  }),
  appKey: z.string(),
  appHash: z.string(),
  origin: z.string(),
});
