name: PROD
on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read

jobs:
  enforce-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from staging
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          HEAD_BRANCH="${{ github.event.pull_request.head.ref }}"
          if [[ "$BASE_BRANCH" == "main" && "$HEAD_BRANCH" != "staging" ]]; then
            echo "❌ Pull Requests para a branch 'main' só podem vir da branch 'staging'."
            exit 1
          fi
